const path = require('path');
const typeScript = require('typescript');

// Should be generated by Beemo beforehand!
// eslint-disable-next-line
const config = require(path.join(process.cwd(), 'tsconfig.json'));

module.exports = {
  process(src, filePath) {
    if (filePath.endsWith('.ts') || filePath.endsWith('.tsx')) {
      return typeScript.transpile(src, config.compilerOptions, filePath, []);
    }

    return src;
  },
};
